# Generated by Django 5.2.5 on 2025-09-06 17:46

import cloudinary.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beheavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beheavior_name', models.CharField()),
                ('beheavior_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Año de edad')),
                ('age_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Mes de edad')),
                ('genre', models.CharField(choices=[('H', 'Macho'), ('M', 'Hembra')], max_length=1, verbose_name='Genero')),
                ('adoption_state', models.BooleanField(default=False, help_text='True si esta adptado', verbose_name='Estado de adopcion')),
                ('size', models.CharField(choices=[('S', 'Chico'), ('M', 'Mediano'), ('L', 'Grande')], max_length=1, verbose_name='Tamaño')),
                ('arrive_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de llegada')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('beheaviors', models.ManyToManyField(to='dogs_api.beheavior')),
            ],
            options={
                'verbose_name': 'Perro',
                'verbose_name_plural': 'Perros',
                'db_table': 'perros',
            },
        ),
        migrations.CreateModel(
            name='Dog_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_primary', models.BooleanField(default=False, help_text='True si es la imagen principal')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dogs_api.dog')),
            ],
            options={
                'verbose_name': 'Foto de perro',
                'verbose_name_plural': 'Fotos de perros',
                'db_table': 'fotos_perros',
            },
        ),
    ]
