# Generated by Django 5.2.5 on 2025-09-10 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beheavior',
            options={'verbose_name': 'Comportamiento', 'verbose_name_plural': 'Comportamientos'},
        ),
        migrations.AlterField(
            model_name='dog',
            name='adoption_state',
            field=models.BooleanField(default=False, help_text='Seleccionar si esta adptado', verbose_name='Estado de adopcion'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age_month',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Mes de edad'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age_year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Año de edad'),
        ),
        migrations.AlterField(
            model_name='dog_image',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Seleccionar si es la imagen principal'),
        ),
        migrations.AlterModelTable(
            name='beheavior',
            table='comportamientos',
        ),
    ]
