# Generated by Django 5.2.5 on 2025-09-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0002_alter_beheavior_options_alter_dog_adoption_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
