# Generated by Django 5.2.6 on 2025-09-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0003_alter_dog_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dog_image',
            new_name='DogImage',
        ),
        migrations.AlterField(
            model_name='beheavior',
            name='beheavior_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Comportamiento'),
        ),
        migrations.AlterField(
            model_name='beheavior',
            name='beheavior_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre del Comportamiento'),
        ),
    ]
