# Generated by Django 5.2.6 on 2025-09-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0005_alter_dog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beheavior',
            name='beheavior_description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción del Comportamiento'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='genre',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1, verbose_name='Genero'),
        ),
    ]
