# Generated by Django 5.2.6 on 2025-10-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0006_alter_beheavior_beheavior_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='section',
            field=models.CharField(choices=[('1', 'Sección 1'), ('2', 'Sección 2'), ('3', 'Sección 3'), ('4', 'Sección 4'), ('5', 'Sección 5')], default='0', max_length=1, verbose_name='Sección'),
        ),
    ]
