# Generated by Django 5.2.7 on 2025-10-21 19:33

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0007_dog_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='beheaviors',
            field=models.ManyToManyField(to='dogs_api.beheavior', verbose_name='Comportamientos'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='section',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1, verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='dogimage',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dogs_api.dog', verbose_name='Perro'),
        ),
        migrations.AlterField(
            model_name='dogimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Archivo de imagen'),
        ),
        migrations.AlterField(
            model_name='dogimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Seleccionar si es la imagen principal', verbose_name='Principal'),
        ),
    ]
