# Generated by Django 5.2.7 on 2025-11-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0008_alter_dog_beheaviors_alter_dog_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beheavior',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color'),
        ),
    ]
