# Generated by Django 5.2.7 on 2025-12-17 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0009_beheavior_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='life_stage',
            field=models.CharField(blank=True, choices=[('CACHORRO', 'Cachorro'), ('JOVEN', 'Joven'), ('ADULTO', 'Adulto'), ('ADULTO_MAYOR', 'Adulto Mayor')], max_length=15, null=True, verbose_name='Etapa de vida'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age_month',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Mes de edad'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age_year',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Año de edad'),
        ),
    ]
