# Generated by Django 5.2.7 on 2025-12-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0010_dog_life_stage_alter_dog_age_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='life_stage',
            field=models.CharField(choices=[('CACHORRO', 'Cachorro'), ('JOVEN', 'Joven'), ('ADULTO', 'Adulto'), ('ADULTO_MAYOR', 'Adulto Mayor')], default='ADULTO', max_length=15, verbose_name='Etapa de vida'),
        ),
    ]
