# Generated by Django 5.2.7 on 2025-12-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_api', '0011_alter_dog_life_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='beheaviors',
            field=models.ManyToManyField(blank=True, to='dogs_api.beheavior', verbose_name='Comportamientos'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='life_stage',
            field=models.CharField(choices=[('CACHORRO', 'Cachorro'), ('JOVEN', 'Joven'), ('ADULTO', 'Adulto'), ('ADULTO_MAYOR', 'Adulto Mayor')], max_length=15, verbose_name='Etapa de vida'),
        ),
    ]
