# Generated by Django 5.2.5 on 2025-09-06 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_record',
            fields=[
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dogs_api.dog')),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('vaccined', models.BooleanField(default=False, help_text='Marca si este perrito tiene completo su esquema de Vacunación', verbose_name='Vacunado')),
                ('sterilized', models.BooleanField(default=False, help_text='Marca si este perrito ya ha sido esterilizado', verbose_name='Esterilizado')),
                ('dewormed', models.BooleanField(default=False, help_text='Marca si este perrito ya ha sido desparacitado', verbose_name='Desparacitado')),
                ('diseases', models.CharField(blank=True, default='', help_text='Anota las enfermedades que padece', max_length=250, verbose_name='Enfermedades')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Peso')),
                ('report', models.TextField(blank=True, default='', help_text='Aqui puedes poner todos los reportes del seguimiento de la salud del perrito', verbose_name='Reportes')),
                ('next_dose', models.DateTimeField(blank=True, help_text='Si el perrito esta sobre tratamiento, pon aqui la fecha y hora de la siguiente dosis que debe de tomar', null=True, verbose_name='Siguiente Dosis')),
            ],
            options={
                'verbose_name': 'Registro Medico',
                'verbose_name_plural': 'Registros Medicos',
            },
        ),
    ]
