# Generated by Django 5.2.5 on 2025-09-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_record',
            name='diseases',
            field=models.CharField(blank=True, default='', help_text='Anota las enfermedades que padece, si no tiene ninguna, dejar en blanco', max_length=250, verbose_name='Enfermedades'),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='weight',
            field=models.PositiveSmallIntegerField(help_text='En Kilogramos', verbose_name='Peso'),
        ),
    ]
