# Generated by Django 5.2.7 on 2025-10-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet_api', '0002_alter_medical_record_diseases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_record',
            name='weight',
        ),
    ]
