import type { Metadata } from "next";

import "@/styles/globals.css";
import "@/styles/CustomCheckbox.css";
import Nav from "@/components/layout/Nav";
import Footer from "@/components/layout/Footer";
import PageWrapper from '@/components/layout/PageWrapper';
import { Providers } from "./providers";
import {myFont} from '@/app/fonts';




export const metadata: Metadata = {
  title: "Esperanza Canina",
  description: "Generated by create next app",
  icons: "/images/logo.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${myFont.variable}`} >
      <head>
        <meta charSet="UTF-8" />
      </head>
      <body className={`${myFont.variable} antialiased`}>
        <Providers>
          <Nav />
          <PageWrapper>
            {children}
          </PageWrapper>
          <Footer />
        </Providers>
      </body>

    </html>
  );
}
