// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { PerritosAdoptCreateData, PerritosAdoptCreateErrors, PerritosAdoptCreateResponses, PerritosListData, PerritosListResponses, PerritosRetrieveData, PerritosRetrieveResponses, PerritosTopRetrieveData, PerritosTopRetrieveResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Lista todos los perros, con filtros y paginación
 */
export const perritosList = <ThrowOnError extends boolean = false>(options?: Options<PerritosListData, ThrowOnError>) => {
    return (options?.client ?? client).get<PerritosListResponses, unknown, ThrowOnError>({
        url: '/api/perritos/',
        ...options
    });
};

/**
 * Detalle de un perro por ID
 */
export const perritosRetrieve = <ThrowOnError extends boolean = false>(options: Options<PerritosRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<PerritosRetrieveResponses, unknown, ThrowOnError>({
        url: '/api/perritos/{id}/',
        ...options
    });
};

/**
 * Adoptar un perro
 * Recibe el formulario de adopción para un perro.
 */
export const perritosAdoptCreate = <ThrowOnError extends boolean = false>(options: Options<PerritosAdoptCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<PerritosAdoptCreateResponses, PerritosAdoptCreateErrors, ThrowOnError>({
        url: '/api/perritos/adopt/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Lista solo los primeros 3 perros, los que acaban de ser agregados
 */
export const perritosTopRetrieve = <ThrowOnError extends boolean = false>(options?: Options<PerritosTopRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<PerritosTopRetrieveResponses, unknown, ThrowOnError>({
        url: '/api/perritos/top/',
        ...options
    });
};

