// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type DetailedDog = {
    readonly id: number;
    /**
     * Nombre
     */
    name?: string;
    readonly size_display: string;
    readonly beheaviors: Array<DetailedDogBehavior>;
    readonly dog_life_stage: string;
    readonly images: Array<DogImages>;
    readonly genre_display: string;
    /**
     * Descripcion
     */
    description?: string;
};

export type DetailedDogBehavior = {
    readonly id: number;
    /**
     * Nombre del Comportamiento
     */
    beheavior_name: string;
    /**
     * Descripción del Comportamiento
     */
    beheavior_description?: string;
};

export type DetailedDogResponse = {
    data: DetailedDog;
};

export type DogImages = {
    readonly id: number;
    readonly url: string;
};

export type DogList = {
    readonly id: number;
    /**
     * Nombre
     */
    name: string;
    readonly size_display: string;
    readonly beheaviors: Array<SimpleDogBehavior>;
    readonly dog_life_stage: string;
    readonly primary_image: string;
    readonly genre_display: string;
};

export type DogTop = {
    readonly id: number;
    /**
     * Nombre
     */
    name?: string;
    readonly primary_image: string;
};

export type DogTopResponse = {
    data: Array<DogTop>;
};

export type PaginatedDogListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    data: Array<DogList>;
};

export type SimpleDogBehavior = {
    readonly id: number;
    /**
     * Nombre del Comportamiento
     */
    beheavior_name: string;
};

export type DetailedDogWritable = {
    /**
     * Nombre
     */
    name?: string;
    /**
     * Descripcion
     */
    description?: string;
};

export type DetailedDogBehaviorWritable = {
    /**
     * Nombre del Comportamiento
     */
    beheavior_name: string;
    /**
     * Descripción del Comportamiento
     */
    beheavior_description?: string;
};

export type DogListWritable = {
    /**
     * Nombre
     */
    name?: string;
};

export type DogTopWritable = {
    /**
     * Nombre
     */
    name?: string;
};

export type SimpleDogBehaviorWritable = {
    /**
     * Nombre del Comportamiento
     */
    beheavior_name: string;
};

export type PerritosListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Comportamientos del perro.
         */
        beheaviors?: string;
        /**
         * Género del perro
         */
        genre?: 'Hembra' | 'Macho';
        /**
         * Etapa de vida del perro
         */
        life_stage?: 'Adulto' | 'Adulto Mayor' | 'Cachorro' | 'Joven';
        /**
         * Un número de página dentro del conjunto de resultados paginado.
         */
        page?: number;
        /**
         * Un término de búsqueda.
         */
        search?: string;
        /**
         * Tamaño del perro
         */
        size?: 'Chico' | 'Grande' | 'Mediano';
    };
    url: '/api/perritos/';
};

export type PerritosListResponses = {
    200: PaginatedDogListList;
};

export type PerritosListResponse = PerritosListResponses[keyof PerritosListResponses];

export type PerritosRetrieveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/perritos/{id}/';
};

export type PerritosRetrieveResponses = {
    200: DetailedDogResponse;
};

export type PerritosRetrieveResponse = PerritosRetrieveResponses[keyof PerritosRetrieveResponses];

export type PerritosTopRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/perritos/top/';
};

export type PerritosTopRetrieveResponses = {
    200: DogTopResponse;
};

export type PerritosTopRetrieveResponse = PerritosTopRetrieveResponses[keyof PerritosTopRetrieveResponses];

export type SchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'af' | 'ar' | 'ar-dz' | 'ast' | 'az' | 'be' | 'bg' | 'bn' | 'br' | 'bs' | 'ca' | 'ckb' | 'cs' | 'cy' | 'da' | 'de' | 'dsb' | 'el' | 'en' | 'en-au' | 'en-gb' | 'eo' | 'es' | 'es-ar' | 'es-co' | 'es-mx' | 'es-ni' | 'es-ve' | 'et' | 'eu' | 'fa' | 'fi' | 'fr' | 'fy' | 'ga' | 'gd' | 'gl' | 'he' | 'hi' | 'hr' | 'hsb' | 'hu' | 'hy' | 'ia' | 'id' | 'ig' | 'io' | 'is' | 'it' | 'ja' | 'ka' | 'kab' | 'kk' | 'km' | 'kn' | 'ko' | 'ky' | 'lb' | 'lt' | 'lv' | 'mk' | 'ml' | 'mn' | 'mr' | 'ms' | 'my' | 'nb' | 'ne' | 'nl' | 'nn' | 'os' | 'pa' | 'pl' | 'pt' | 'pt-br' | 'ro' | 'ru' | 'sk' | 'sl' | 'sq' | 'sr' | 'sr-latn' | 'sv' | 'sw' | 'ta' | 'te' | 'tg' | 'th' | 'tk' | 'tr' | 'tt' | 'udm' | 'ug' | 'uk' | 'ur' | 'uz' | 'vi' | 'zh-hans' | 'zh-hant';
    };
    url: '/api/schema/';
};

export type SchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SchemaRetrieveResponse = SchemaRetrieveResponses[keyof SchemaRetrieveResponses];
