// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
    // Si alguien lo quiere correr dentro de docker, activa esto
    // baseUrl: 'http://api:8000' | 'http://localhost:8000' | (string & {});
};

export type CuidadoYCalidadDeVida = {
    dogcare_field1?: string | null;
    dogcare_field2?: boolean | null;
    dogcare_field3?: string | null;
    dogcare_field4?: boolean | null;
    dogcare_field5?: string | null;
    dogcare_field6?: string | null;
    dogcare_field7?: string | null;
    dogcare_field8?: string | null;
    dogcare_field9?: string | null;
};

export type DatosDelAnimalInput = {
    dog_id: number;
};

export type DatosDelSolicitante = {
    adpt_name: string;
    adpt_age: number;
    adpt_address: string;
    adpt_form_field1?: string | null;
    adpt_form_field2?: string | null;
    adpt_form_field3?: string | null;
    adpt_form_field4?: string | null;
    adpt_form_field5?: string | null;
    adpt_form_field6?: string | null;
    adpt_form_field7?: boolean | null;
    adopt_form_field8?: string | null;
};

export type DetailedDog = {
    readonly id: number;
    /**
     * Nombre
     */
    name?: string;
    readonly size_display: string;
    readonly beheaviors: Array<DetailedDogBehavior>;
    readonly dog_life_stage: string;
    readonly images: Array<DogImages>;
    readonly genre_display: string;
    /**
     * Descripcion
     */
    description?: string;
    readonly section_display: string;
};

export type DetailedDogBehavior = {
    readonly id: number;
    /**
     * Nombre del Comportamiento
     */
    beheavior_name: string;
    /**
     * Descripción del Comportamiento
     */
    beheavior_description?: string;
};

export type DetailedDogResponse = {
    data: DetailedDog;
};

export type DogImages = {
    readonly id: number;
    readonly url: string;
};

export type DogList = {
    readonly id: number;
    /**
     * Nombre
     */
    name?: string;
    readonly size_display: string;
    readonly beheaviors: Array<SimpleDogBehavior>;
    readonly dog_life_stage: string;
    readonly primary_image: string;
    readonly genre_display: string;
    readonly section_display: string;
};

export type DogTop = {
    readonly id: number;
    /**
     * Nombre
     */
    name?: string;
    readonly primary_image: string;
};

export type DogTopResponse = {
    data: Array<DogTop>;
};

export type EspacioDondeVivira = {
    living_form_field1?: string | null;
    living_form_field3?: boolean | null;
    living_form_field4?: string | null;
    living_form_field5?: string | null;
    living_form_field6?: boolean | null;
    living_form_field7?: string | null;
    living_form_field8?: string | null;
    living_form_field9?: string | null;
    living_form_field10?: string | null;
    living_form_field11?: string | null;
};

export type FormularioAdopcion = {
    datos_del_animal: DatosDelAnimalInput;
    datos_del_solicitante: DatosDelSolicitante;
    sobre_el_espacio: EspacioDondeVivira;
    sobre_el_cuidado: CuidadoYCalidadDeVida;
};

export type PaginatedDogListList = {
    count: number;
    total_pages: number,
    current_page: number,
    next?: string | null;
    previous?: string | null;
    data: Array<DogList>;
};

export type SimpleDogBehavior = {
    readonly id: number;
    /**
     * Nombre del Comportamiento
     */
    beheavior_name: string;
};


export type PerritosListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Comportamientos del perro.
         */
        beheaviors?: string;
        /**
         * Género del perro
         */
        genre?: 'Hembra' | 'Macho';
        /**
         * Etapa de vida del perro
         */
        life_stage?: 'Adulto' | 'Adulto Mayor' | 'Cachorro' | 'Joven';
        /**
         * Un número de página dentro del conjunto de resultados paginado.
         */
        page?: number;
        /**
         * Un término de búsqueda.
         */
        search?: string;
        /**
         * Sección del perro (1 a 5).
         */
        section?: 'Sección 1' | 'Sección 2' | 'Sección 3' | 'Sección 4' | 'Sección 5';
        /**
         * Tamaño del perro
         */
        size?: 'Chico' | 'Grande' | 'Mediano';
    };
    url: '/api/perritos/';
};

export type PerritosListResponses = {
    200: PaginatedDogListList;
};

export type PerritosListResponse = PerritosListResponses[keyof PerritosListResponses];

export type PerritosRetrieveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/perritos/{id}/';
};

export type PerritosRetrieveResponses = {
    200: DetailedDogResponse;
};

export type PerritosRetrieveResponse = PerritosRetrieveResponses[keyof PerritosRetrieveResponses];

export type PerritosAdoptCreateData = {
    body: FormularioAdopcion;
    path?: never;
    query?: never;
    url: '/api/perritos/adopt/';
};

export type PerritosAdoptCreateErrors = {
    /**
     * Datos inválidos en el formulario.
     */
    400: unknown;
};

export type PerritosAdoptCreateResponses = {
    /**
     * Formulario recibido con éxito.
     */
    200: unknown;
};

export type PerritosTopRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/perritos/top/';
};

export type PerritosTopRetrieveResponses = {
    200: DogTopResponse;
};

export type PerritosTopRetrieveResponse = PerritosTopRetrieveResponses[keyof PerritosTopRetrieveResponses];

