services:
  redis:
    image: redis:7
    container_name: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 2s
      retries: 10
    restart: always
  api:
    container_name: api
    build: 
      context: ../backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
    - "8000:8000"
    env_file:
      - ../backend/.env.prod
    restart: always
  qcluster:
    container_name: qcluster
    build:
      context: ../backend
    command: python manage.py qcluster
    env_file:
      - ../backend/.env.prod
    depends_on:
      redis:
        condition: service_healthy
    restart: always  