// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiPerritosAdoptCreateData, ApiPerritosAdoptCreateErrors, ApiPerritosAdoptCreateResponses, ApiPerritosListData, ApiPerritosListResponses, ApiPerritosRetrieveData, ApiPerritosRetrieveResponses, ApiPerritosTopRetrieveData, ApiPerritosTopRetrieveResponses, ApiRegistrosMedicosCreateData, ApiRegistrosMedicosCreateResponses, ApiRegistrosMedicosListData, ApiRegistrosMedicosListResponses, ApiRegistrosMedicosRetrieveData, ApiRegistrosMedicosRetrieveResponses, ApiSchemaRetrieveData, ApiSchemaRetrieveResponses, VisitasTestRetrieveData, VisitasTestRetrieveResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Lista todos los perros, con filtros y paginación
 */
export const apiPerritosList = <ThrowOnError extends boolean = false>(options?: Options<ApiPerritosListData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiPerritosListResponses, unknown, ThrowOnError>({
        url: '/api/perritos/',
        ...options
    });
};

/**
 * Detalle de un perro por ID
 */
export const apiPerritosRetrieve = <ThrowOnError extends boolean = false>(options: Options<ApiPerritosRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<ApiPerritosRetrieveResponses, unknown, ThrowOnError>({
        url: '/api/perritos/{id}/',
        ...options
    });
};

/**
 * Adoptar un perro
 * Recibe el formulario de adopción para un perro.
 */
export const apiPerritosAdoptCreate = <ThrowOnError extends boolean = false>(options: Options<ApiPerritosAdoptCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiPerritosAdoptCreateResponses, ApiPerritosAdoptCreateErrors, ThrowOnError>({
        url: '/api/perritos/adopt/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Lista solo los primeros 3 perros, los que acaban de ser agregados
 */
export const apiPerritosTopRetrieve = <ThrowOnError extends boolean = false>(options?: Options<ApiPerritosTopRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiPerritosTopRetrieveResponses, unknown, ThrowOnError>({
        url: '/api/perritos/top/',
        ...options
    });
};

export const apiRegistrosMedicosList = <ThrowOnError extends boolean = false>(options?: Options<ApiRegistrosMedicosListData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiRegistrosMedicosListResponses, unknown, ThrowOnError>({
        url: '/api/registros-medicos/',
        ...options
    });
};

export const apiRegistrosMedicosCreate = <ThrowOnError extends boolean = false>(options: Options<ApiRegistrosMedicosCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiRegistrosMedicosCreateResponses, unknown, ThrowOnError>({
        url: '/api/registros-medicos/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const apiRegistrosMedicosRetrieve = <ThrowOnError extends boolean = false>(options: Options<ApiRegistrosMedicosRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<ApiRegistrosMedicosRetrieveResponses, unknown, ThrowOnError>({
        url: '/api/registros-medicos/{dog}/',
        ...options
    });
};

/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.
 *
 * - YAML: application/vnd.oai.openapi
 * - JSON: application/vnd.oai.openapi+json
 */
export const apiSchemaRetrieve = <ThrowOnError extends boolean = false>(options?: Options<ApiSchemaRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiSchemaRetrieveResponses, unknown, ThrowOnError>({
        url: '/api/schema/',
        ...options
    });
};

export const visitasTestRetrieve = <ThrowOnError extends boolean = false>(options?: Options<VisitasTestRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<VisitasTestRetrieveResponses, unknown, ThrowOnError>({
        url: '/visitas-test/',
        ...options
    });
};
