// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type CuidadoYCalidadDeVida = {
    dogcare_field1?: string | null;
    dogcare_field2?: boolean | null;
    dogcare_field3?: string | null;
    dogcare_field4?: boolean | null;
    dogcare_field5?: string | null;
    dogcare_field6?: string | null;
    dogcare_field7?: string | null;
    dogcare_field8?: string | null;
    dogcare_field9?: string | null;
};

export type DatosDelAnimalInput = {
    dog_id: number;
};

export type DatosDelSolicitante = {
    adpt_name: string;
    adpt_age: number;
    adpt_address: string;
    adpt_form_field1?: string | null;
    adpt_form_field2?: string | null;
    adpt_form_field3?: string | null;
    adpt_form_field4?: string | null;
    adpt_form_field5?: string | null;
    adpt_form_field6?: string | null;
    adpt_form_field7?: boolean | null;
    adopt_form_field8?: string | null;
};

export type DetailedDog = {
    readonly id: number;
    /**
     * Nombre
     */
    name?: string;
    readonly size_display: string;
    readonly beheaviors: Array<DetailedDogBehavior>;
    readonly life_stage_display: string;
    readonly images: Array<DogImages>;
    readonly genre_display: string;
    /**
     * Descripcion
     */
    description?: string;
    readonly section_display: string;
};

export type DetailedDogBehavior = {
    readonly id: number;
    /**
     * Nombre del Comportamiento
     */
    beheavior_name: string;
    /**
     * Descripción del Comportamiento
     */
    beheavior_description?: string;
    color?: string;
};

export type DetailedDogResponse = {
    data: DetailedDog;
};

export type DogImages = {
    readonly id: number;
    readonly url: string;
};

export type DogList = {
    readonly id: number;
    /**
     * Nombre
     */
    name?: string;
    readonly size_display: string;
    readonly beheaviors: Array<SimpleDogBehavior>;
    readonly life_stage_display: string;
    readonly primary_image: string;
    readonly genre_display: string;
    readonly section_display: string;
};

export type DogTop = {
    readonly id: number;
    /**
     * Nombre
     */
    name?: string;
    readonly primary_image: string;
};

export type DogTopResponse = {
    data: Array<DogTop>;
};

export type EspacioDondeVivira = {
    living_form_field1?: string | null;
    living_form_field3?: boolean | null;
    living_form_field4?: string | null;
    living_form_field5?: string | null;
    living_form_field6?: boolean | null;
    living_form_field7?: string | null;
    living_form_field8?: string | null;
    living_form_field9?: string | null;
    living_form_field10?: string | null;
    living_form_field11?: string | null;
};

export type FormularioAdopcion = {
    datos_del_animal: DatosDelAnimalInput;
    datos_del_solicitante: DatosDelSolicitante;
    sobre_el_espacio: EspacioDondeVivira;
    sobre_el_cuidado: CuidadoYCalidadDeVida;
};

export type MedicalRecord = {
    dog: number;
    readonly dog_name: string;
    readonly last_update_date: string;
    /**
     * Vacunado
     * Marca si este perrito tiene completo su esquema de Vacunación
     */
    vaccined?: boolean;
    /**
     * Esterilizado
     * Marca si este perrito ya ha sido esterilizado
     */
    sterilized?: boolean;
    /**
     * Desparacitado
     * Marca si este perrito ya ha sido desparacitado
     */
    dewormed?: boolean;
    /**
     * Enfermedades
     * Anota las enfermedades que padece, si no tiene ninguna, dejar en blanco
     */
    diseases?: string;
    /**
     * Reportes
     * Aqui puedes poner todos los reportes del seguimiento de la salud del perrito
     */
    report?: string;
    /**
     * Siguiente Dosis
     * Si el perrito esta sobre tratamiento, pon aqui la fecha y hora de la siguiente dosis que debe de tomar
     */
    next_dose?: string | null;
};

export type PaginatedDogListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DogList>;
};

export type SimpleDogBehavior = {
    readonly id: number;
    /**
     * Nombre del Comportamiento
     */
    beheavior_name: string;
    color?: string;
};

export type DetailedDogWritable = {
    /**
     * Nombre
     */
    name?: string;
    /**
     * Descripcion
     */
    description?: string;
};

export type DetailedDogBehaviorWritable = {
    /**
     * Nombre del Comportamiento
     */
    beheavior_name: string;
    /**
     * Descripción del Comportamiento
     */
    beheavior_description?: string;
    color?: string;
};

export type DogListWritable = {
    /**
     * Nombre
     */
    name?: string;
};

export type DogTopWritable = {
    /**
     * Nombre
     */
    name?: string;
};

export type MedicalRecordWritable = {
    dog: number;
    /**
     * Vacunado
     * Marca si este perrito tiene completo su esquema de Vacunación
     */
    vaccined?: boolean;
    /**
     * Esterilizado
     * Marca si este perrito ya ha sido esterilizado
     */
    sterilized?: boolean;
    /**
     * Desparacitado
     * Marca si este perrito ya ha sido desparacitado
     */
    dewormed?: boolean;
    /**
     * Enfermedades
     * Anota las enfermedades que padece, si no tiene ninguna, dejar en blanco
     */
    diseases?: string;
    /**
     * Reportes
     * Aqui puedes poner todos los reportes del seguimiento de la salud del perrito
     */
    report?: string;
    /**
     * Siguiente Dosis
     * Si el perrito esta sobre tratamiento, pon aqui la fecha y hora de la siguiente dosis que debe de tomar
     */
    next_dose?: string | null;
};

export type SimpleDogBehaviorWritable = {
    /**
     * Nombre del Comportamiento
     */
    beheavior_name: string;
    color?: string;
};

export type ApiPerritosListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Comportamientos del perro.
         */
        beheaviors?: string;
        /**
         * Género del perro
         */
        genre?: 'Hembra' | 'Macho';
        /**
         * Etapa de vida del perro
         */
        life_stage?: 'Adulto' | 'Adulto Mayor' | 'Cachorro' | 'Joven';
        /**
         * Un número de página dentro del conjunto de resultados paginado.
         */
        page?: number;
        /**
         * Un término de búsqueda.
         */
        search?: string;
        /**
         * Sección del perro (1 a 5).
         */
        section?: 'Sección 1' | 'Sección 2' | 'Sección 3' | 'Sección 4' | 'Sección 5';
        /**
         * Tamaño del perro
         */
        size?: 'Chico' | 'Grande' | 'Mediano';
    };
    url: '/api/perritos/';
};

export type ApiPerritosListResponses = {
    200: PaginatedDogListList;
};

export type ApiPerritosListResponse = ApiPerritosListResponses[keyof ApiPerritosListResponses];

export type ApiPerritosRetrieveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/perritos/{id}/';
};

export type ApiPerritosRetrieveResponses = {
    200: DetailedDogResponse;
};

export type ApiPerritosRetrieveResponse = ApiPerritosRetrieveResponses[keyof ApiPerritosRetrieveResponses];

export type ApiPerritosAdoptCreateData = {
    body: FormularioAdopcion;
    path?: never;
    query?: never;
    url: '/api/perritos/adopt/';
};

export type ApiPerritosAdoptCreateErrors = {
    /**
     * Datos inválidos en el formulario.
     */
    400: unknown;
};

export type ApiPerritosAdoptCreateResponses = {
    /**
     * Formulario recibido con éxito.
     */
    200: unknown;
};

export type ApiPerritosTopRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/perritos/top/';
};

export type ApiPerritosTopRetrieveResponses = {
    200: DogTopResponse;
};

export type ApiPerritosTopRetrieveResponse = ApiPerritosTopRetrieveResponses[keyof ApiPerritosTopRetrieveResponses];

export type ApiRegistrosMedicosListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/registros-medicos/';
};

export type ApiRegistrosMedicosListResponses = {
    200: Array<MedicalRecord>;
};

export type ApiRegistrosMedicosListResponse = ApiRegistrosMedicosListResponses[keyof ApiRegistrosMedicosListResponses];

export type ApiRegistrosMedicosCreateData = {
    body: MedicalRecordWritable;
    path?: never;
    query?: never;
    url: '/api/registros-medicos/';
};

export type ApiRegistrosMedicosCreateResponses = {
    201: MedicalRecord;
};

export type ApiRegistrosMedicosCreateResponse = ApiRegistrosMedicosCreateResponses[keyof ApiRegistrosMedicosCreateResponses];

export type ApiRegistrosMedicosRetrieveData = {
    body?: never;
    path: {
        /**
         * Un valor único que identifique este Registro Medico.
         */
        dog: number;
    };
    query?: never;
    url: '/api/registros-medicos/{dog}/';
};

export type ApiRegistrosMedicosRetrieveResponses = {
    200: MedicalRecord;
};

export type ApiRegistrosMedicosRetrieveResponse = ApiRegistrosMedicosRetrieveResponses[keyof ApiRegistrosMedicosRetrieveResponses];

export type ApiSchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'es';
    };
    url: '/api/schema/';
};

export type ApiSchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type ApiSchemaRetrieveResponse = ApiSchemaRetrieveResponses[keyof ApiSchemaRetrieveResponses];

export type VisitasTestRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/visitas-test/';
};

export type VisitasTestRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};
